# fly.toml app configuration file generated for shy-sun-4141 on 2023-09-04T15:43:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-sun-4141"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[process]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"

[env]
  PORT = "5000"

[[services]]
  http_checks = []
  internal_port = 5000
  process = ["app"]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
