on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Halojaa"
      - name: health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokemon-ta6d.onrender.com/health
          max-attempts: 3
          retry-delay: 59s
